### ISSUE TITLE
Git diff not displaying in the preview

### ISSUE THREAD

**Issue by keatsfonam** [wfxr/forgit#245]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
gd is not showing anything in the preview pane. The file is detected. All other commands are correctly displaying the preview pane

Seems that it is similar to https://github.com/wfxr/forgit/issues/203 which was closed. There are no spaces in my filename.

To reproduce:
- clone latest (2872548)
```
mkdir /tmp/git-test
cd /tmp/git-test
git init
touch testfile
git add testfile
git commit -m "test"
echo "newline" > testfile
gd
```

Here is `gd`
![Screen Shot 2022-11-03 at 12 06 06 PM](https://user-images.githubusercontent.com/2251630/199811984-94a6bc23-9eb0-41d1-87e6-c472343d0a27.png)

Here is `git diff`
![Screen Shot 2022-11-03 at 12 06 27 PM](https://user-images.githubusercontent.com/2251630/199812037-bd212297-fcf1-4940-a94e-da91b7b6cebb.png)

Here is `glo` properly displaying
![Screen Shot 2022-11-03 at 12 06 57 PM](https://user-images.githubusercontent.com/2251630/199812127-a13194b8-56e0-4bd7-9b66-f072cc4d3011.png)

**Comment by carlfriedrich** [comment]
@keatsfonam Thanks for your bug report. I actually cannot reproduce this with zsh on Linux, `gd` works fine here with your proposed steps:

![grafik](https://user-images.githubusercontent.com/45259958/199953535-ef913eb6-ed58-4a4f-902f-143a3d53dda4.png)

Did this use to work in former versions of forgit? If so, can you maybe bisect this to a specific forgit version?

**Comment by carlfriedrich** [comment]
@keatsfonam Ah, from your screenshot I see that there's obviously a bug in the file list itself, which explains why the preview is not shown:

![grafik](https://user-images.githubusercontent.com/45259958/199954140-6b7af09d-636c-4a6a-8c15-207cbbc75058.png)

The arrow is inserted in [these code lines](https://github.com/wfxr/forgit/blob/2872548075e63bc83a0b960e2813b16571998563/forgit.plugin.zsh#L93..L94):

```
eval "git diff --name-status $commits -- ${files[*]} | sed -E 's/^([[:alnum:]]+)[[:space:]]+(.*)$/[\1]\t\2/'" |
    sed 's/\t/  ->  /2' | expand -t 8 |
```

The second `sed` command should replace a tab (which appears in the git output if files are renamed) with the `  ->  ` string. Obviously this command does not the right thing in your environment. Can you verify this by giving me the output of the following two commands:

```
echo -e "M\ttestfile" | sed 's/\t/  ->  /2' 
echo -e "R100\ttestfile\tmyfile" | sed 's/\t/  ->  /2'
```

It should look like this:

![grafik](https://user-images.githubusercontent.com/45259958/199957671-6e0a5aea-c140-480c-9d56-a7f1f160a518.png)

**Comment by carlfriedrich** [comment]
@keatsfonam Thanks for your feedback. Unfortunately I don't have a Mac to verify this. Can you check if adding `-E` to sed changes anything?

```
echo -E "M\ttestfile" | sed 's/\t/  ->  /2' 
echo -E "R100\ttestfile\tmyfile" | sed 's/\t/  ->  /2'
```

**Comment by keatsfonam** [comment]
I think you mixed up the -E on your sed and echo. Neither fix the problem. However I just found that adding a $ in front seems to resolve the problem as far as I can tell

![Screen Shot 2022-11-18 at 1 01 36 PM](https://user-images.githubusercontent.com/2251630/202801699-63cbf2c6-23fe-4217-8083-4c4f17c8c2b3.png)

**Comment by carlfriedrich** [comment]
@keatsfonam Oh yes, I indeed mixed up the arguments in my example. Edited the post accordingly.

However, thanks for bringing up that solution! I will prepare a PR for that.

**Comment by carlfriedrich** [comment]
@keatsfonam I pushed PR #250 with a fix for this. Can you checkout the branch and verify that it fixes the issue for you?

**Comment by keatsfonam** [comment]
The issue still occurs in the line above adding the tab
`sed -E 's/^([[:alnum:]]+)[[:space:]]+(.*)$/[\1]\t\2/'"`


![Screen Shot 2022-11-30 at 11 53 52 AM](https://user-images.githubusercontent.com/2251630/204895206-ba0a5356-8d5b-4cb1-8218-152c4d67faa2.png)


Using a $ to quote this one did not work (output is just []). I just got it working fine for me by just using spaces instead of a \t character. Not sure if this is a universal solution. 

```
diff --git a/bin/git-forgit b/bin/git-forgit
index c79a40e..8717251 100755
--- a/bin/git-forgit
+++ b/bin/git-forgit
@@ -123,7 +123,7 @@ _forgit_diff() {
         $FORGIT_DIFF_FZF_OPTS
         --prompt=\"$commits > \"
     "
-    eval "git diff --name-status $commits -- ${files[*]} | sed -E 's/^([[:alnum:]]+)[[:space:]]+(.*)$/[\1]\t\2/'" |
+    eval "git diff --name-status $commits -- ${files[*]} | sed -E 's/^([[:alnum:]]+)[[:space:]]+(.*)$/[\1]	\2/'" |
         sed $'s/\t/  ->  /2' | expand -t 8 |
         FZF_DEFAULT_OPTS="$opts" fzf
     fzf_exit_code=$?

```

**Comment by carlfriedrich** [comment]
@keatsfonam Thanks a lot for your feedback. I updated the branch in #250 with your proposed solution. Can you check again?

**Comment by keatsfonam** [comment]
@carlfriedrich Works great, thanks.
